//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoVendas.Cap03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_VENDASEntities : DbContext
    {
        public DB_VENDASEntities()
            : base("name=DB_VENDASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> TBCategorias { get; set; }
        public virtual DbSet<Cliente> TBClientes { get; set; }
        public virtual DbSet<Item> TBItens { get; set; }
        public virtual DbSet<Pedido> TBPedidos { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
        public object Pedidos { get; internal set; }
    }
}
